nginx:
    image: looploy/nginx:1.17.1-a
    container_name: nginx_throttle
    environment:
        NGINX_LOG_OUTPUT: 'file'
        NGINX_LOG_TYPE: 'main'
        NGINX_USER: 'root'
        VIEW_CONFIG: "yes"
        PROXY_MODE: "yes"
        USE_NGINX_THROTTLE: "yes"
        # NGINX_THROTTLE_BY_URI: "yes"
        NGINX_RATE_LIMIT: "700r/s"
        NGINX_BURST: "5"
        GRPC_LISTEN_PORT: 7100
        GRPC_PROXY_MODE: "yes"
#        PROXY_PASS_ENDPOINT: "grpc://prep:7100"
        USE_VTS_STATUS: "yes"
        TZ: "GMT-9"
        PREP_MODE: "yes"
        PREP_LISTEN_PORT: 9000
        NODE_CONTAINER_NAME: "prep"
#        PREP_PROXY_PASS_ENDPOINT: "http://prep:9000"
#        PREP_NODE_LIST_API: "prep:9000/api/v3"
        PREP_NGINX_ALLOWIP: "yes"
        NGINX_ALLOW_IP: "0.0.0.0/0"
#        LOCATION: "location ~ /api/ws/* {proxy_pass http://_upstreamer;proxy_http_version 1.1;proxy_set_header Upgrade $$http_upgrade;proxy_set_header Connection 'Upgrade'; proxy_read_timeout 1800s;} location ~ /api/node/* {proxy_pass http://_upstreamer;proxy_http_version 1.1;proxy_set_header Upgrade $$http_upgrade;proxy_set_header Connection 'Upgrade'; proxy_read_timeout 1800s;} "
        NGINX_LOG_FORMAT: '$$realip_remote_addr $$remote_addr  $$remote_user [$$time_local] $$request $$status $$body_bytes_sent $$http_referer "$$http_user_agent" $$http_x_forwarded_for $$request_body'
      volumes:
         - ./data/loopchain/nginx:/var/log/nginx
         - ./manual_acl:/etc/nginx/manual_acl
      ports:
         - '7100:7100'
         - '9000:9000'
