#!/usr/bin/env php
<?php

/**
 * Allows to get the content of a php-fpm environment configuration file
 */
class PhpFpmEnvironment {
    /**
     * The temporary directory, used in TMP, TEMP and TMPDIR environment variables
     * @var string
     */
    const TMP = '/tmp';

    /**
     * The path where to find executables, where sbin should be excluded if you don't run PHP as root.
     * @var string
     */
    const PATH = '/usr/local/bin:/usr/bin:/bin';

    /**
     * The environment variables to discard
     * @var Array
     */
    const VARIABLES_TO_DISCARD = [
        '_',           // The caller executable script, not pertinent
        'HOME',        // Set correctly by php-fpm
        'TERM',        // Not pertinent in server context
        'MYSQL_ENV_MYSQL_ROOT_PASSWORD', // from --link …:mysql
        'HOSTNAME',
		'PHP_INI_DIR',
		'PHP5_KEY',
		'FPM_GROUP',
		'LS_COLORS',
		'PHP_LIB',
		'DOCKERIZE_VERSION',
		'PATH',
		'PHP7_KEY',
		'PWD',
		'SHLVL',
		'PHP_BUILD_DEPS',
		'PHALCON_VER',
		'affinity:container',
		'LESSOPEN',
		'FPM_LISTEN',
		'LESSCLOSE',
		'PHP_VERSION',
		'PHP_EXTRA_CONFIGURE_ARGS',
		'FPM_USER',
		'OLDPWD',
		'PHP_SELF',
		'SCRIPT_NAME',
		'SCRIPT_FILENAME',
		'PATH_TRANSLATED',
		'DOCUMENT_ROOT',
		'REQUEST_TIME_FLOAT',
		'REQUEST_TIME',
		'argv',
		'argc',
		'TMP',
		'TEMP',
		'TMPDIR'
    ];

    /**
     * Gets an environment array from the current process environment,
     * with PATH and temp variablesfiltered.
     *
     * @return Array
     */
    public static function getEnvironmentVariables () {
        $variables = [];

        foreach ($_SERVER as $key => $value) {
            if (!static::mustIgnoreVariable($key)) {
	            $variables[$key] = $value;
            }
        }

        static::addHardcodedEnvironmentVariables($variables);

        return $variables;
    }

    /**
     * Adds hardcoded and always wanted environment variables
     * (path, temporary directory) to the specified array.
     *
     * @paran array $variables the array to add the variables to
     */
    public static function addHardcodedEnvironmentVariables (&$variables) {
        static::addTempEnvironmentVariables ($variables);
        static::addPathEnvironmentVariables ($variables);
    }

    /**
     * Adds temporary directory environment variables to the specified array.
     *
     * @paran array $variables the array to add the variables to
     */
    public static function addTempEnvironmentVariables (&$variables) {
        $variables['TMP'] = static::TMP;
        $variables['TEMP'] = static::TMP;
        $variables['TMPDIR'] = static::TMP;
    }

    /**
     * Adds temporary directory environment variables to the specified array.
     *
     * @paran array $variables the array to add the variables to
     */
    public static function addPathEnvironmentVariables (&$variables) {
        $variables['PATH'] = static::PATH;
    }

    /**
     * Determines if the variable name must be ignored
     *
     * @return bool true if the variable must be ignored; otherwise, false.
     */
    public static function mustIgnoreVariable ($variableName) {
        return in_array($variableName, static::VARIABLES_TO_DISCARD);
    }

    /**
     * Prints the environment
     */
    public static function printConfig () {
        $variables = static::getEnvironmentVariables();

        foreach ($variables as $key => $value) {
            echo 'env["', $key, '"] = "', $value, '"', PHP_EOL;
        }
    }
}

PhpFpmEnvironment::printConfig();
